//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 02:04:20 PM PDT 
//


package gov.vha.isaac.ochre.deployment.terminolgy.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}AllowEmpty"/>
 *         &lt;element ref="{}IsList"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}Inverse"/>
 *           &lt;sequence minOccurs="0">
 *             &lt;element ref="{}PropertyType"/>
 *             &lt;element ref="{}PropertyValue"/>
 *           &lt;/sequence>
 *         &lt;/sequence>
 *         &lt;element ref="{}IncludeWithChange" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "allowEmpty",
    "isList",
    "inverse",
    "propertyType",
    "propertyValue",
    "includeWithChange"
})
@XmlRootElement(name = "Relationship")
public class Relationship {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "AllowEmpty")
    protected boolean allowEmpty;
    @XmlElement(name = "IsList")
    protected boolean isList;
    @XmlElement(name = "Inverse")
    protected Boolean inverse;
    @XmlElement(name = "PropertyType")
    protected String propertyType;
    @XmlElement(name = "PropertyValue")
    protected String propertyValue;
    @XmlElement(name = "IncludeWithChange")
    protected String includeWithChange;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the allowEmpty property.
     * 
     */
    public boolean isAllowEmpty() {
        return allowEmpty;
    }

    /**
     * Sets the value of the allowEmpty property.
     * 
     */
    public void setAllowEmpty(boolean value) {
        this.allowEmpty = value;
    }

    /**
     * Gets the value of the isList property.
     * 
     */
    public boolean isIsList() {
        return isList;
    }

    /**
     * Sets the value of the isList property.
     * 
     */
    public void setIsList(boolean value) {
        this.isList = value;
    }

    /**
     * Gets the value of the inverse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInverse() {
        return inverse;
    }

    /**
     * Sets the value of the inverse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInverse(Boolean value) {
        this.inverse = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the propertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * Sets the value of the propertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyValue(String value) {
        this.propertyValue = value;
    }

    /**
     * Gets the value of the includeWithChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeWithChange() {
        return includeWithChange;
    }

    /**
     * Sets the value of the includeWithChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeWithChange(String value) {
        this.includeWithChange = value;
    }

}
